[package]
name = "verifiable_random_function"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2curves = "0.1.0"
sha2 = "0.10"
rand_core = "0.6"

[dev-dependencies]
ark-std = "0.4.0"